apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: patnaikshekhar/custom-service-mesh-xds-server
    context: .
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: '*.js'
        dest: /app
deploy:
  kubectl:
    manifests:
      - k8s.yaml